apiVersion: v1
kind: Service
metadata:
  name: digital-inheritance-vault-service
  namespace: seclock
spec:
  type: LoadBalancer
  selector:
    app: digital-inheritance-vault
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
